Add create button and page
Team-uMigrate/umigrate pull request #254
Opened 2020-10-16 00:10 UTC by gracenng

2020-10-16 19:36 UTC, trentstauff commented on mobile/src/src/components/Create/CreatePage.jsx
> +
delete extra white space

2020-10-16 19:37 UTC, trentstauff commented on mobile/src/src/components/Create/CreatePage.jsx
> +
delete line

2020-10-16 19:38 UTC, trentstauff commented on mobile/src/src/components/Create/index.jsx
> +export default CreatePage;
add newline at end of file

2020-10-16 19:38 UTC, trentstauff commented on mobile/src/src/components/Create/CreatePage.jsx
> +});
newline end of file

2020-10-16 19:39 UTC, trentstauff commented on mobile/src/src/navigators/TabNavigator.jsx
> +      {/* <LinearGradient
Do you need this comment?

2020-10-16 19:40 UTC, trentstauff commented on mobile/src/src/navigators/TabNavigator.jsx
> +          tabBarIcon: ({ color}) => (
As you can see, ({ color}) isnt centered. Im going to stop the review now, install the prettier extension and just go through your files youve touched and do ctrl+S, and upload the changes

2020-10-16 19:40 UTC, trentstauff commented on mobile/src/src/navigators/TabNavigator.jsx
> +          tabBarIcon: ({ color}) => (
Other than that- i havent tested the code locally yet, so i will do that and let you know. Code looks good though grace, good work.

2020-10-16 19:41 UTC, trentstauff requested changes
Just install prettier and clean code up- i also need to test it after so dont merge yet

2020-10-18 20:03 UTC, gracenng commented
![image](https://user-images.githubusercontent.com/42276283/96378639-75bdc800-115b-11eb-9a82-9ad48559b705.png)
 tested this morning after re-cloning

2020-10-19 03:56 UTC, trentstauff approved these changes
Looks good, nice work Grace.

2020-10-19 03:57 UTC, merged