API: References to shared items in message objects #241
Team-uMigrate/umigrate pull request #449
Opened 2021-05-31 19:56 UTC by NihalPotdar

2021-06-03 23:16 UTC, deandrebaker requested changes
@NihalPotdar looking good so far! I noticed that the html file had a lot of formatting changes. Maybe you can undo those?

2021-06-03 23:16 UTC, deandrebaker commented on api/src/messaging/templates/room.html
> +        websocketProtocol + window.location.host + "/ws/messaging/" + roomId
Why'd you delete the last '/' .

2021-06-03 23:16 UTC, deandrebaker commented on api/src/messaging/consumers.py
> +        )
Interesting syntax. Isn't this just 3 assignment statements? You used more lines for this.

2021-06-03 23:16 UTC, deandrebaker commented on api/src/messaging/consumers.py
> +from asgiref.sync import sync_to_async
I don't think we need to use sync_to_async. We can use the database_sync_to_async wrapper that is already imported

2021-06-03 23:16 UTC, deandrebaker commented on api/src/messaging/consumers.py
> +                content_type = await sync_to_async(ContentType.objects.get)(
We should use database_sync_to_async for this instead of sync_to_async.

2021-06-03 23:16 UTC, deandrebaker commented on api/src/messaging/consumers.py
> +                }
I'm not sure if we care about handling exceptions just yet. I think for now it's fine to just assume you're getting valid data in text_json. I'll add another story to handle exceptions in the chat consumer later.

2021-06-06 15:48 UTC, deandrebaker requested changes
@NihalPotdar looks much better! I think you just forgot to remove an html tag at the bottom of room.html. Once you fix it, it should be good to merge in.

2021-06-06 15:48 UTC, deandrebaker commented on api/src/messaging/templates/room.html
> +</html>
I think you can delete this

2021-06-06 19:23 UTC, NihalPotdar commented on api/src/messaging/templates/room.html
> +</html>
Done, deleted the additional tag

2021-06-06 19:48 UTC, deandrebaker approved these changes

2021-06-06 19:49 UTC, merged