Feature/common style sheets
Team-uMigrate/umigrate pull request #475
Opened 2021-06-23 00:22 UTC by magovansh9

Created new StyleSheets for jsx files with overlapping css.

2021-06-23 00:30 UTC, magovansh9 commented
The naming of the stylesheet jsx files can be improved, please suggest appropriate names.

2021-06-23 02:26 UTC, deandrebaker requested changes
@magovansh9 looking really good! Just made some suggestions on things we can clean up.

2021-06-23 02:26 UTC, deandrebaker commented on app/src/src/stylesheets/views/views.jsx
> +/* Used in AdView, EventView, ListingView, PollView */
We can delete these 2 lines.

2021-06-23 02:26 UTC, deandrebaker commented on app/src/src/stylesheets/views/views.jsx
> +
You can add a comment under this line saying what this stylesheet is for (e.g. Styles for Shared Item views)

2021-06-23 02:26 UTC, deandrebaker commented on app/src/src/stylesheets/views/views.jsx
> +const commonViewStyles = StyleSheet.create({
We can add 'export' infront of const here to save lines.
`export const commonViewStyles = StyleSheet.create({`

Also, we should rename this constant to something like 'sharedItemViewStyles'

2021-06-23 02:26 UTC, deandrebaker commented on app/src/src/stylesheets/views/views.jsx
> +  export {commonViewStyles}
We can delete this line

2021-06-23 02:26 UTC, deandrebaker commented on app/src/src/stylesheets/tabs/tabs.jsx
> +
Do we need this file? Nothing here is exported.

2021-06-23 02:26 UTC, deandrebaker commented on app/src/src/screens/likes/LikesScreen.jsx
> +
These changes do not belong in this PR. Please undo this.

2021-06-23 02:26 UTC, deandrebaker commented on app/src/src/screens/notifications/NotificationsScreen.jsx
> +import {styles} from '../../stylesheets/messaging/messaging.jsx';
Isn't the messaging.jsx file empty? How can we import 'styles' from it?

2021-06-23 02:26 UTC, deandrebaker commented on app/src/src/stylesheets/likesAndComments/likesAndComments.jsx
> +const styles = StyleSheet.create({
We can use the 'export' keyword infront of 'const' to save lines.

Also, we should give this a more descriptive name than just 'styles'

2021-06-23 02:26 UTC, deandrebaker commented on app/src/src/stylesheets/createItem/createItem.jsx
> +const styles = StyleSheet.create({
We can use the 'export' keyword infront of 'const' to save lines.

Also, we should give this a more descriptive name than just 'styles'

2021-06-23 02:26 UTC, deandrebaker commented on app/src/src/components/views/PostView.jsx
> +
We can delete this line

2021-06-23 02:26 UTC, deandrebaker commented on app/src/src/components/views/LikedUserView.jsx
> +    </>
We do not need to wrap this in a react fragment (<></>). We can simply just return the View component

2021-06-23 02:26 UTC, deandrebaker commented on app/src/src/components/views/EventView.jsx
> +
We can delete this line.

2021-06-23 02:26 UTC, deandrebaker commented on app/src/src/components/views/CommentBar.jsx
> +              });
These changes do not belong in this PR. Please undo this.

2021-06-23 18:34 UTC, trentstauff commented on app/src/src/components/views/CommentBar.jsx
> +          <Text onPress={() => {}} style={styles.likesText}>
Why was this TODO comment removed?

2021-07-07 02:28 UTC, deandrebaker approved these changes

2021-07-07 02:52 UTC, merged