Feature/userview modal
Team-uMigrate/umigrate pull request #523
Opened 2021-07-08 19:04 UTC by joryclements

Added feature to bring up user profile upon clicking their icon
https://expo.io/@joryclements/umigrate-userviewmodal
Closes #283

2021-07-10 19:04 UTC, trentstauff submitted a review, later dismissed
Overall, great PR and awesome work for a nice first actual ticket!

Looks like the formatting checks are failing.

Run `npm run format:unix` in the src directory to fix this (https://github.com/Team-uMigrate/umigrate/wiki/uMigrate-App).

2021-07-10 19:04 UTC, trentstauff commented on app/src/src/components/views/EventView.jsx
> +        onPress = { () => userView.setUser(creator) } >
remove starting and trailing spaces ie { () => ... (creator) } (the ones beside the curly braces) for consistency

2021-07-11 17:03 UTC, deandrebaker requested changes
@joryclements looking good so far! I added some requested changes below.

In addition, you forgot to update the AdView component with the TouchableOpacity that you added to the PostView.

2021-07-11 17:03 UTC, deandrebaker commented on app/src/src/contexts/UserViewContext.jsx
> +// A context provider that stores the user whose profile is to be shown
Follow the same commenting structure and coding practices as the other Contexts.

2021-08-18 00:56 UTC, deandrebaker approved these changes

2021-08-28 17:32 UTC, Apsd1109 approved these changes
was fully reviewed by Deandre and Jory, ready to pull according to both.

2021-08-28 17:34 UTC, merged